# This is a basic workflow to help you get started with Actions

name: CI-Marx

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      # - run: echo "//registry.npmjs.org/:_authToken=2f934392-639b-4117-a388-3cd60bf4f053" > ~/.npmrc
      # - run: cat ~/.npmrc
    
        # env: # More info about the environment variables in the README
        #     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Leave this as is, it's automatically generated
        #     NPM_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }} 

      - run: npm i
      - run: npm run build-
      - run: pwd /dist/marx-editor/
      - run: cd /dist/marx-editor/
      - run: pwd 
      - run: ls
      - run: npm pack && npm publish
      # - run: echo "//registry.npmjs.org/:_authToken=ed2ee00d-87bd-4e04-a514-8d6866a2d0f1" > ~/.npmrc
     


